//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smdpp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nozzle
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> PositionX { get; set; }
        public Nullable<decimal> PositionY { get; set; }
        public Nullable<decimal> PositionZ { get; set; }
        public string Description { get; set; }
    }
}
