//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smdpp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> Offset { get; set; }
        public Nullable<int> Checksum { get; set; }
        public Nullable<int> Size { get; set; }
    }
}
